run: build
	source ./build.sh && run
runDocker: build
	source ./build.sh && runDocker
build: 
	source ./build.sh && build
push: build
	source ./build.sh && push
installArgo:
	source ./build.sh && installArgo